package com.myreminder.app.ui.theme

import androidx.compose.ui.graphics.Color

val PriorityHigh = Color(0xFFE53935)
val PriorityMedium = Color(0xFFFDD835)
val PriorityLow = Color(0xFF43A047)
val CompletedGray = Color(0xFF9E9E9E)

val md_theme_light_primary = Color(0xFF1B5E20)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA5F29B)
val md_theme_light_onPrimaryContainer = Color(0xFF002204)
val md_theme_light_secondary = Color(0xFF52634F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD5E8CE)
val md_theme_light_onSecondaryContainer = Color(0xFF101F10)
val md_theme_light_tertiary = Color(0xFF386567)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBCEBEB)
val md_theme_light_onTertiaryContainer = Color(0xFF002021)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_outline = Color(0xFF72796F)
val md_theme_light_background = Color(0xFFFCFDF6)
val md_theme_light_onBackground = Color(0xFF1A1C19)
val md_theme_light_surface = Color(0xFFFCFDF6)
val md_theme_light_onSurface = Color(0xFF1A1C19)
val md_theme_light_surfaceVariant = Color(0xFFDFE4D7)
val md_theme_light_onSurfaceVariant = Color(0xFF424940)
val md_theme_light_inverseSurface = Color(0xFF2F312D)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1EB)
val md_theme_light_inversePrimary = Color(0xFF8AD581)

val md_theme_dark_primary = Color(0xFF8AD581)
val md_theme_dark_onPrimary = Color(0xFF00390A)
val md_theme_dark_primaryContainer = Color(0xFF005313)
val md_theme_dark_onPrimaryContainer = Color(0xFFA5F29B)
val md_theme_dark_secondary = Color(0xFFB9CCB3)
val md_theme_dark_onSecondary = Color(0xFF243423)
val md_theme_dark_secondaryContainer = Color(0xFF3B4B38)
val md_theme_dark_onSecondaryContainer = Color(0xFFD5E8CE)
val md_theme_dark_tertiary = Color(0xFFA0CFCF)
val md_theme_dark_onTertiary = Color(0xFF003738)
val md_theme_dark_tertiaryContainer = Color(0xFF1E4E50)
val md_theme_dark_onTertiaryContainer = Color(0xFFBCEBEB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_outline = Color(0xFF8C9388)
val md_theme_dark_background = Color(0xFF1A1C19)
val md_theme_dark_onBackground = Color(0xFFE2E3DD)
val md_theme_dark_surface = Color(0xFF1A1C19)
val md_theme_dark_onSurface = Color(0xFFE2E3DD)
val md_theme_dark_surfaceVariant = Color(0xFF424940)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BC)
val md_theme_dark_inverseSurface = Color(0xFFE2E3DD)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C19)
val md_theme_dark_inversePrimary = Color(0xFF1B5E20)
