#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for handling when clauses in case
case "$(uname)" in
CYGWIN* | MINGW* | MSYS*)
    APP_HOME="$(cd -P -- "$(dirname -- "$app_path")" && pwd -W)"
    ;;
*)
    while [ -h "$app_path" ] ; do
        ls=$( ls -ld -- "$app_path" )
        link=$( expr "$ls" : '.*-> \(.*\)$' )
        if expr "$link" : '/.*' > /dev/null; then
            app_path="$link"
        else
            app_path="$(dirname -- "$app_path")/$link"
        fi
    done
    APP_HOME="$(cd -P -- "$(dirname -- "$app_path")" && pwd)"
    ;;
esac

APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$CYGWIN" = "false" -a "$DARWIN" = "false" -a "$NONSTOP" = "false" ] ; then
    case $MAX_FD in
      max*)
        # In POSIX sh, limit is a reserved word
        MAX_FD=$( ulimit -H -n )
        if [ $? -eq 0 ] ; then
            if [ "$MAX_FD" = "unlimited" ] ; then
                # Some systems report unlimited, which can't be set with ulimit -n
                MAX_FD=""
            fi
        else
            warn "Could not query maximum file descriptor limit: $MAX_FD"
        fi
        ;;
    esac
    if [ -n "$MAX_FD" ] ; then
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    fi
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Auto-download gradle-wrapper.jar if missing
if [ ! -e "$CLASSPATH" ]; then
    mkdir -p "$APP_HOME/gradle/wrapper"
    echo "Downloading gradle-wrapper.jar..."
    JAR_URL="https://raw.githubusercontent.com/gradle/gradle/v8.11.1/gradle/wrapper/gradle-wrapper.jar"
    if command -v curl >/dev/null 2>&1; then
        curl -sSL -f "$JAR_URL" -o "$CLASSPATH" || true
    elif command -v wget >/dev/null 2>&1; then
        wget -q "$JAR_URL" -O "$CLASSPATH" || true
    fi
fi

# Split arguments properly using eval so that quotes inside DEFAULT_JVM_OPTS are handled correctly
eval "set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \"-Dorg.gradle.appname=$APP_BASE_NAME\" -classpath \"$CLASSPATH\" org.gradle.wrapper.GradleWrapperMain \"\$@\""

exec "$JAVACMD" "$@"
